//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsStorage.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public long FilmID { get; set; }
        public string FilmName { get; set; }
        public int ReleaseYear { get; set; }
        public int fk_GenreID { get; set; }
        public int fk_UserID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FilmDescription { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual User User { get; set; }
    }
}
